language: python
python:
  - "3.5"
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - pip install cookiecutter
script:
  - cd $TRAVIS_BUILD_DIR
  - cookiecutter --no-input https://github.com/PrashntS/plump-sr.git
  - cd plumpsr
  - npm install
  - brunch b
notifications:
  email:
    recipients: prashantsinha@outlook.com
    on_success: change
    on_failure: change
