language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install cookiecutter
script:
  - cd $TRAVIS_BUILD_DIR
  - cookiecutter --no-input https://github.com/PrashntS/plump-sr.git
  - cd plump-sr
  - npm install
  - npm run build
notifications:
  email:
    recipients: prashantsinha@outlook.com
    on_success: change
    on_failure: change
